version: '3'
services:
  floating-ip:
    image: osixia/keepalived:latest
    #ports:
    #- "8444:8444"
    volumes:
    - ./template/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf
    cap_add:
    - NET_ADMIN
    network_mode: "host"

